version: 0.2

phases:
  install:
    commands:
      - echo installing NGINX
      - sudo yum update -y
      - sudo amazon-linux-extras enable nginx1
      - sudo yum install -y nginx
  build:
    commands:
      - echo Build started on `date`
      - sudo cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - index.html
